name: CI

on:
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    name: Execute tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase 
        uses: actions/checkout@v2
      - name: Setup the node js.
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build the application
        run: | 
          npm install
      - name: Execute tests
        run: |
          npm run test
