on:
  push:
    branches:    
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create-libs:
    name: Create Javascript
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase 
        uses: actions/checkout@v2
        with:
          ref: build
      - name: Setup the node js.
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Reset to the latest codebase.
        run: |
          git config --global user.name 'Action Service Account'
          git config --global user.email 'no-reply@github.com'
          git fetch
          git reset --hard origin/main
      - name: Build the application
        run: | 
          npm install
          npm run build
      - name: Commit libs
        run: |
          mv lib/.gitignore lib/bkp.gitignore
          git add lib/app.bundle*
          mv lib/bkp.gitignore lib/.gitignore
          git commit -m "Automated library commit"
          git push -f origin build
